server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/club?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: qwe123.0+-
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-implementations: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_empty
# 图片上传路径
web:
  uploadpath: D:/images/
  load-path: D:/images/

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n'